# app/services/medicine_database_extended.py
# 200+ COMMON MEDICINES - Complete Database
# Categories: Pain, Antibiotics, Diabetes, BP, Heart, Mental Health, etc.

MEDICINES_EXTENDED = {
    # ==========================================
    # PAIN RELIEVERS & NSAIDs
    # ==========================================
    "diclofenac": {
        "name": "Diclofenac",
        "brands": ["Voltaren", "Voveran", "Cataflam", "Diclomax"],
        "category": "NSAID Pain Reliever",
        "uses": ["Arthritis pain", "Back pain", "Migraine", "Dental pain", "Gout", "Muscle pain"],
        "adult_dose": "50mg 2-3 times daily or 100mg SR once daily",
        "child_dose": "Not recommended under 14 years",
        "pregnancy": "AVOID especially 3rd trimester",
        "side_effects": ["Stomach pain", "Nausea", "Heartburn", "Dizziness", "Headache"],
        "warnings": ["Take with food", "Avoid in stomach ulcer", "Caution in asthma", "Kidney risk with long use"],
        "missed_dose": "Take as soon as remembered with food. Skip if almost time for next dose.",
        "storage": "Room temperature, away from moisture",
    },
    "naproxen": {
        "name": "Naproxen",
        "brands": ["Aleve", "Naprosyn", "Anaprox"],
        "category": "NSAID Pain Reliever",
        "uses": ["Arthritis", "Menstrual cramps", "Gout", "Tendonitis", "Back pain"],
        "adult_dose": "250-500mg twice daily",
        "child_dose": "5-7mg/kg twice daily (over 2 years)",
        "pregnancy": "AVOID especially 3rd trimester",
        "side_effects": ["Stomach pain", "Heartburn", "Drowsiness", "Headache"],
        "warnings": ["Take with food/milk", "Avoid with other NSAIDs", "Caution in heart disease"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    "tramadol": {
        "name": "Tramadol",
        "brands": ["Ultram", "Tramazac", "Tramacet"],
        "category": "Opioid Pain Reliever (Prescription only)",
        "uses": ["Moderate to severe pain", "Post-surgery pain", "Chronic pain"],
        "adult_dose": "50-100mg every 4-6 hours, max 400mg/day",
        "child_dose": "Not recommended under 12 years",
        "pregnancy": "AVOID - may harm baby",
        "side_effects": ["Nausea", "Constipation", "Dizziness", "Drowsiness", "Headache"],
        "warnings": ["Addictive", "Don't use with alcohol", "May cause seizures", "Don't stop suddenly"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
        "storage": "Room temperature, secure from misuse",
    },
    
    # ==========================================
    # ANTIBIOTICS
    # ==========================================
    "doxycycline": {
        "name": "Doxycycline",
        "brands": ["Doxy", "Vibramycin", "Doxine"],
        "category": "Antibiotic (Tetracycline)",
        "uses": ["Acne", "Chest infections", "Lyme disease", "Malaria prevention", "UTI", "Chlamydia"],
        "adult_dose": "100-200mg once or twice daily",
        "child_dose": "Not recommended under 8 years (affects teeth/bones)",
        "pregnancy": "AVOID - affects fetal bone development",
        "side_effects": ["Nausea", "Sun sensitivity", "Yeast infection", "Esophageal irritation"],
        "warnings": ["Take with food and water", "Avoid sun exposure", "Don't take with dairy/antacids", "Complete full course"],
        "missed_dose": "Take as soon as remembered. Complete full course.",
        "course_duration": "Usually 7-14 days. COMPLETE FULL COURSE.",
    },
    "metronidazole": {
        "name": "Metronidazole",
        "brands": ["Flagyl", "Metrogyl", "Metron"],
        "category": "Antibiotic (Anaerobic bacteria & parasites)",
        "uses": ["Dental infections", "Diarrhea (C.diff)", "Amoebiasis", "Giardia", "Bacterial vaginosis", "H.pylori"],
        "adult_dose": "400-500mg every 8 hours",
        "child_dose": "7.5mg/kg every 8 hours",
        "pregnancy": "Generally safe after 1st trimester (consult doctor)",
        "side_effects": ["Metallic taste", "Nausea", "Dark urine", "Headache"],
        "warnings": ["AVOID ALCOHOL completely (severe reaction)", "Complete full course", "Take with food"],
        "missed_dose": "Take as soon as remembered. Complete full course.",
        "course_duration": "Usually 5-10 days.",
    },
    "cephalexin": {
        "name": "Cephalexin",
        "brands": ["Keflex", "Sporidex", "Cephadex"],
        "category": "Antibiotic (Cephalosporin)",
        "uses": ["Skin infections", "UTI", "Respiratory infections", "Ear infections", "Dental infections"],
        "adult_dose": "250-500mg every 6-12 hours",
        "child_dose": "25-50mg/kg/day divided in 2-4 doses",
        "pregnancy": "Generally safe",
        "side_effects": ["Diarrhea", "Nausea", "Rash", "Stomach pain"],
        "warnings": ["Complete full course", "Tell doctor if penicillin allergic"],
        "missed_dose": "Take as soon as remembered. Complete full course.",
        "course_duration": "Usually 7-14 days.",
    },
    
    # ==========================================
    # DIABETES MEDICINES
    # ==========================================
    "glimepiride": {
        "name": "Glimepiride",
        "brands": ["Amaryl", "Glimer", "Glimiprex"],
        "category": "Diabetes Medicine (Sulfonylurea)",
        "uses": ["Type 2 diabetes"],
        "adult_dose": "1-8mg once daily with breakfast",
        "child_dose": "Not recommended",
        "pregnancy": "Insulin preferred during pregnancy",
        "side_effects": ["Low blood sugar", "Weight gain", "Nausea", "Headache"],
        "warnings": ["Take WITH breakfast", "Risk of hypoglycemia", "Avoid alcohol", "Monitor blood sugar"],
        "missed_dose": "Take with next meal. Skip if almost time for next dose.",
        "best_time": "With breakfast (first meal of day)",
    },
    "pioglitazone": {
        "name": "Pioglitazone",
        "brands": ["Actos", "Pioglit", "Pioz"],
        "category": "Diabetes Medicine (Thiazolidinedione)",
        "uses": ["Type 2 diabetes"],
        "adult_dose": "15-45mg once daily",
        "child_dose": "Not recommended",
        "pregnancy": "Consult doctor",
        "side_effects": ["Weight gain", "Fluid retention", "Bone fractures (women)", "Headache"],
        "warnings": ["Not for heart failure patients", "Monitor liver", "May increase fracture risk"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
        "best_time": "Same time each day, with or without food",
    },
    "empagliflozin": {
        "name": "Empagliflozin",
        "brands": ["Jardiance", "Empa"],
        "category": "Diabetes Medicine (SGLT2 Inhibitor)",
        "uses": ["Type 2 diabetes", "Heart failure", "Kidney protection"],
        "adult_dose": "10-25mg once daily in morning",
        "child_dose": "Not recommended",
        "pregnancy": "AVOID in 2nd/3rd trimester",
        "side_effects": ["UTI", "Genital infections", "Increased urination", "Thirst", "Low BP"],
        "warnings": ["Can cause dehydration", "Monitor for infections", "Check kidney function"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
        "best_time": "Morning, with or without food",
    },
    
    # ==========================================
    # BLOOD PRESSURE MEDICINES
    # ==========================================
    "losartan": {
        "name": "Losartan",
        "brands": ["Cozaar", "Losar", "Losacar"],
        "category": "Blood Pressure Medicine (ARB)",
        "uses": ["High blood pressure", "Kidney protection (diabetes)", "Heart failure"],
        "adult_dose": "25-100mg once daily",
        "child_dose": "As prescribed (over 6 years)",
        "pregnancy": "AVOID - can harm unborn baby",
        "side_effects": ["Dizziness", "Back pain", "Cold symptoms"],
        "warnings": ["Avoid pregnancy", "Monitor kidney function and potassium", "Can cause dizziness"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Same time every day",
    },
    "telmisartan": {
        "name": "Telmisartan",
        "brands": ["Micardis", "Telma", "Telmikind"],
        "category": "Blood Pressure Medicine (ARB)",
        "uses": ["High blood pressure", "Heart attack/stroke prevention"],
        "adult_dose": "20-80mg once daily",
        "child_dose": "Not recommended",
        "pregnancy": "AVOID - can harm unborn baby",
        "side_effects": ["Dizziness", "Back pain", "Sinus infection"],
        "warnings": ["Avoid pregnancy", "Monitor kidney function", "Don't take with potassium supplements"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Same time every day, with or without food",
    },
    "atenolol": {
        "name": "Atenolol",
        "brands": ["Tenormin", "Atenol", "Tenolol"],
        "category": "Blood Pressure Medicine (Beta Blocker)",
        "uses": ["High blood pressure", "Angina", "Migraine prevention", "After heart attack"],
        "adult_dose": "25-100mg once daily",
        "child_dose": "As prescribed by cardiologist",
        "pregnancy": "Consult doctor - may affect baby growth",
        "side_effects": ["Fatigue", "Cold hands/feet", "Slow heartbeat", "Dizziness", "Sleep problems"],
        "warnings": ["Don't stop suddenly", "May mask low blood sugar signs", "Caution in asthma"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Morning, same time every day",
    },
    
    # ==========================================
    # CHOLESTEROL MEDICINES
    # ==========================================
    "rosuvastatin": {
        "name": "Rosuvastatin",
        "brands": ["Crestor", "Rosuvas", "Rozavel"],
        "category": "Cholesterol Medicine (Statin)",
        "uses": ["High cholesterol", "Prevent heart disease", "Reduce triglycerides"],
        "adult_dose": "5-40mg once daily",
        "child_dose": "Not recommended",
        "pregnancy": "AVOID - can harm unborn baby",
        "side_effects": ["Muscle pain", "Headache", "Stomach pain", "Weakness"],
        "warnings": ["Report muscle pain immediately", "Avoid alcohol", "Pregnancy must be avoided"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Evening (body makes cholesterol at night)",
        "monitoring": "Liver function and cholesterol every 3-6 months",
    },
    
    # ==========================================
    # STOMACH / ACID MEDICINES
    # ==========================================
    "pantoprazole": {
        "name": "Pantoprazole",
        "brands": ["Protonix", "Pantop", "Pantocid"],
        "category": "Proton Pump Inhibitor (PPI)",
        "uses": ["GERD", "Stomach ulcer", "Zollinger-Ellison", "H.pylori (with antibiotics)"],
        "adult_dose": "40mg once daily before breakfast",
        "child_dose": "As prescribed",
        "pregnancy": "Generally safe, consult doctor",
        "side_effects": ["Headache", "Diarrhea", "Stomach pain", "Nausea"],
        "warnings": ["Take 30 min before meal", "Long-term use may affect B12/magnesium"],
        "missed_dose": "Take as soon as remembered before next meal.",
        "best_time": "30 minutes before first meal",
    },
    "ranitidine": {
        "name": "Ranitidine (DISCONTINUED in many countries)",
        "brands": ["Zantac", "Rantac", "Aciloc"],
        "category": "H2 Blocker - Acid Reducer",
        "uses": ["Heartburn", "GERD", "Stomach ulcer", "Indigestion"],
        "adult_dose": "150mg twice daily or 300mg at bedtime",
        "child_dose": "As prescribed",
        "pregnancy": "Generally safe",
        "side_effects": ["Headache", "Constipation", "Diarrhea"],
        "warnings": ["Many brands recalled (2020) due to NDMA contamination", "Check if still available in your country"],
        "note": "Many countries have discontinued this medicine. Famotidine is a safer alternative.",
    },
    "famotidine": {
        "name": "Famotidine",
        "brands": ["Pepcid", "Famocid", "Topcid"],
        "category": "H2 Blocker - Acid Reducer",
        "uses": ["Heartburn", "GERD", "Stomach ulcer", "Indigestion"],
        "adult_dose": "20-40mg once or twice daily",
        "child_dose": "As prescribed (over 1 year)",
        "pregnancy": "Generally safe",
        "side_effects": ["Headache", "Constipation", "Diarrhea"],
        "warnings": ["Take as needed or regularly as prescribed"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    "antacids": {
        "name": "Antacids (Calcium/Magnesium/Aluminum)",
        "brands": ["Tums", "Gaviscon", "Mylanta", "Digene", "Gelusil"],
        "category": "Antacid",
        "uses": ["Heartburn", "Indigestion", "Acid reflux (immediate relief)"],
        "adult_dose": "10-20ml or 1-2 tablets as needed, max 4 times/day",
        "child_dose": "Consult pediatrician for children under 12",
        "pregnancy": "Generally safe (calcium-based preferred)",
        "side_effects": ["Constipation (aluminum)", "Diarrhea (magnesium)", "Burping"],
        "warnings": ["Don't take within 2 hours of other medicines", "Short-term use only"],
        "storage": "Room temperature. Shake liquid forms well.",
    },
    
    # ==========================================
    # ALLERGY & COLD MEDICINES
    # ==========================================
    "loratadine": {
        "name": "Loratadine",
        "brands": ["Claritin", "Alavert", "Lorfast"],
        "category": "Antihistamine (Non-drowsy)",
        "uses": ["Allergies", "Hay fever", "Hives", "Itching"],
        "adult_dose": "10mg once daily",
        "child_dose": "5mg once daily (2-12 years)",
        "pregnancy": "Generally safe, consult doctor",
        "side_effects": ["Headache", "Dry mouth", "Nervousness (rare)"],
        "warnings": ["Non-drowsy but can still affect some people"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
    },
    "fexofenadine": {
        "name": "Fexofenadine",
        "brands": ["Allegra", "Fexo", "Fexidine"],
        "category": "Antihistamine (Non-drowsy)",
        "uses": ["Seasonal allergies", "Hives", "Itchy skin"],
        "adult_dose": "120-180mg once daily",
        "child_dose": "30mg twice daily (6 months-2 years), 60mg (2-12 years)",
        "pregnancy": "Generally safe, consult doctor",
        "side_effects": ["Headache", "Dizziness", "Nausea"],
        "warnings": ["Take with water only (fruit juices reduce absorption)"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
    },
    "montelukast": {
        "name": "Montelukast",
        "brands": ["Singulair", "Montair", "Romilast"],
        "category": "Leukotriene Receptor Antagonist",
        "uses": ["Asthma prevention", "Allergic rhinitis", "Exercise-induced asthma"],
        "adult_dose": "10mg once daily in evening",
        "child_dose": "4-5mg once daily (depending on age)",
        "pregnancy": "Generally safe",
        "side_effects": ["Headache", "Stomach pain", "Mood changes (rare but serious)"],
        "warnings": ["FDA black box warning: mental health side effects", "Not for acute asthma attacks"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Evening for asthma, any time for allergies",
    },
    "pseudoephedrine": {
        "name": "Pseudoephedrine",
        "brands": ["Sudafed", "Sinufed", "Coldarin"],
        "category": "Decongestant",
        "uses": ["Nasal congestion", "Sinus pressure", "Cold symptoms"],
        "adult_dose": "60mg every 4-6 hours, max 240mg/day",
        "child_dose": "Not under 4 years. 15-30mg (4-12 years)",
        "pregnancy": "AVOID in 1st trimester. Caution later.",
        "side_effects": ["Increased heart rate", "Insomnia", "Nervousness", "High BP"],
        "warnings": ["Avoid in high BP, heart disease", "Can cause insomnia", "Sold behind counter in many countries"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    
    # ==========================================
    # MENTAL HEALTH MEDICINES
    # ==========================================
    "fluoxetine": {
        "name": "Fluoxetine",
        "brands": ["Prozac", "Fludac", "Flunil"],
        "category": "Antidepressant (SSRI)",
        "uses": ["Depression", "Anxiety", "OCD", "Panic disorder", "Bulimia", "PMDD"],
        "adult_dose": "20-80mg once daily in morning",
        "child_dose": "As prescribed by psychiatrist (over 8 years)",
        "pregnancy": "Consult doctor - benefits vs risks",
        "side_effects": ["Nausea (temporary)", "Insomnia", "Anxiety (initially)", "Sexual dysfunction", "Appetite changes"],
        "warnings": ["Takes 2-6 weeks to work", "Suicide risk in first weeks (young people)", "Don't stop suddenly"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Morning (can cause insomnia if taken at night)",
    },
    "escitalopram": {
        "name": "Escitalopram",
        "brands": ["Lexapro", "Cipralex", "Nexito"],
        "category": "Antidepressant (SSRI)",
        "uses": ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety"],
        "adult_dose": "10-20mg once daily",
        "child_dose": "As prescribed by psychiatrist (over 12 years)",
        "pregnancy": "Consult doctor",
        "side_effects": ["Nausea", "Fatigue", "Insomnia", "Sexual dysfunction", "Weight changes"],
        "warnings": ["Takes 1-4 weeks to work", "Don't stop suddenly (withdrawal)", "Alcohol increases side effects"],
        "missed_dose": "Take as soon as remembered. Skip if almost 24 hours late.",
        "best_time": "Morning or evening (depends on if it causes drowsiness or insomnia)",
    },
    "alprazolam": {
        "name": "Alprazolam",
        "brands": ["Xanax", "Alprax", "Anxit"],
        "category": "Benzodiazepine (Anti-anxiety) - CONTROLLED SUBSTANCE",
        "uses": ["Anxiety", "Panic disorder", "Insomnia (short-term)"],
        "adult_dose": "0.25-0.5mg 2-3 times daily (anxiety), 0.5-1mg at bedtime (panic)",
        "child_dose": "Not recommended",
        "pregnancy": "AVOID - can harm baby, cause withdrawal in newborn",
        "side_effects": ["Drowsiness", "Dizziness", "Memory problems", "Confusion", "Dependence"],
        "warnings": ["HIGHLY ADDICTIVE", "Don't mix with alcohol (deadly)", "Don't stop suddenly (seizures)", "Short-term use only (2-4 weeks)"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
        "storage": "Room temperature, SECURE from others",
    },
    
    # ==========================================
    # ASTHMA & COPD MEDICINES
    # ==========================================
    "budesonide": {
        "name": "Budesonide (Inhaled)",
        "brands": ["Pulmicort", "Budecort", "Symbicort (with formoterol)"],
        "category": "Inhaled Corticosteroid (Preventer)",
        "uses": ["Asthma prevention", "COPD", "Allergic rhinitis (nasal spray)"],
        "adult_dose": "200-800mcg twice daily (inhaled)",
        "child_dose": "As prescribed (usually 100-400mcg twice daily)",
        "pregnancy": "Generally safe - uncontrolled asthma is riskier",
        "side_effects": ["Throat irritation", "Hoarseness", "Oral thrush", "Cough"],
        "warnings": ["Rinse mouth after use", "NOT for acute attacks", "Use daily even if feeling well"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    "ipratropium": {
        "name": "Ipratropium",
        "brands": ["Atrovent", "Ipravent", "Combivent (with salbutamol)"],
        "category": "Bronchodilator (Anticholinergic)",
        "uses": ["COPD", "Asthma (adjunct)", "Runny nose (nasal spray)"],
        "adult_dose": "2 puffs 4 times daily, max 12 puffs/day",
        "child_dose": "As prescribed (over 6 years)",
        "pregnancy": "Generally safe",
        "side_effects": ["Dry mouth", "Cough", "Headache", "Nausea"],
        "warnings": ["Not for acute attacks (slower onset)", "Avoid contact with eyes"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    
    # ==========================================
    # ANTI-EPILEPTIC / SEIZURE MEDICINES
    # ==========================================
    "gabapentin": {
        "name": "Gabapentin",
        "brands": ["Neurontin", "Gabapin", "Gaba"],
        "category": "Anti-epileptic / Nerve Pain",
        "uses": ["Nerve pain", "Epilepsy", "Restless legs syndrome", "Hot flashes"],
        "adult_dose": "300-3600mg/day divided in 3 doses",
        "child_dose": "As prescribed (over 3 years)",
        "pregnancy": "Consult doctor - benefits vs risks",
        "side_effects": ["Dizziness", "Drowsiness", "Weight gain", "Swelling", "Confusion"],
        "warnings": ["Don't stop suddenly (withdrawal)", "May cause dependence", "Avoid alcohol"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    "pregabalin": {
        "name": "Pregabalin",
        "brands": ["Lyrica", "Pregaba", "Maxgalin"],
        "category": "Anti-epileptic / Nerve Pain",
        "uses": ["Nerve pain", "Fibromyalgia", "Epilepsy", "Generalized anxiety"],
        "adult_dose": "150-600mg/day divided in 2-3 doses",
        "child_dose": "As prescribed",
        "pregnancy": "AVOID if possible - may harm baby",
        "side_effects": ["Dizziness", "Drowsiness", "Weight gain", "Blurred vision", "Dry mouth"],
        "warnings": ["May cause dependence", "Don't stop suddenly", "Avoid alcohol", "May affect driving"],
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
    },
    
    # ==========================================
    # ANTI-COAGULANTS (BLOOD THINNERS)
    # ==========================================
    "warfarin": {
        "name": "Warfarin",
        "brands": ["Coumadin", "Warf", "Marevan"],
        "category": "Anticoagulant (Blood Thinner)",
        "uses": ["Prevent blood clots", "Atrial fibrillation", "DVT", "Pulmonary embolism", "Heart valve replacement"],
        "adult_dose": "As per INR levels (usually 1-10mg daily)",
        "child_dose": "As prescribed by specialist",
        "pregnancy": "AVOID - causes birth defects (use heparin instead)",
        "side_effects": ["Bleeding", "Bruising", "Purple toes (rare)"],
        "warnings": ["Regular INR monitoring required", "Many drug/food interactions", "Limit vitamin K foods (consistent intake)", "Wear medical alert bracelet"],
        "missed_dose": "Take as soon as remembered. If missed by >12 hours, skip and call doctor.",
        "monitoring": "INR test regularly (usually every 1-4 weeks)",
        "interactions": "MANY - including aspirin, antibiotics, alcohol, green leafy vegetables",
    },
    "rivaroxaban": {
        "name": "Rivaroxaban",
        "brands": ["Xarelto", "Rivaban"],
        "category": "Anticoagulant (DOAC - Direct Oral Anticoagulant)",
        "uses": ["Prevent blood clots", "Atrial fibrillation", "DVT treatment", "After hip/knee surgery"],
        "adult_dose": "10-20mg once daily with food",
        "child_dose": "Not recommended",
        "pregnancy": "AVOID",
        "side_effects": ["Bleeding", "Bruising", "Nausea"],
        "warnings": ["Take WITH food (evening meal)", "No routine monitoring needed", "Don't stop suddenly"],
        "missed_dose": "Take as soon as remembered. If missed by >12 hours, skip and take next dose.",
        "advantage": "No regular blood tests needed (unlike warfarin)",
    },
    
    # ==========================================
    # VITAMINS & SUPPLEMENTS (MORE)
    # ==========================================
    "folic_acid": {
        "name": "Folic Acid (Vitamin B9)",
        "brands": ["Folvite", "Folacin", "Folitab"],
        "category": "Vitamin Supplement",
        "uses": ["Prevent birth defects (neural tube)", "Anemia", "Pregnancy", "Methotrexate side effects"],
        "adult_dose": "400-800mcg daily. Pregnancy: 400mcg before and during",
        "child_dose": "As prescribed",
        "pregnancy": "ESSENTIAL - start before conception if possible",
        "side_effects": ["Rare at normal doses", "May mask B12 deficiency"],
        "warnings": ["Essential for all women of childbearing age"],
        "best_time": "Any time, with or without food",
    },
    "zinc": {
        "name": "Zinc Supplement",
        "brands": ["Zincovit", "Zinconia", "Zinc gluconate"],
        "category": "Mineral Supplement",
        "uses": ["Immune function", "Wound healing", "Cold duration reduction", "Acne", "Diarrhea in children"],
        "adult_dose": "15-30mg daily (elemental zinc)",
        "child_dose": "5-15mg daily (depending on age)",
        "pregnancy": "Safe within recommended doses",
        "side_effects": ["Nausea (if taken empty stomach)", "Metallic taste", "Copper deficiency (long-term high dose)"],
        "warnings": ["Take with food to avoid nausea", "May reduce antibiotic absorption (separate 2 hours)"],
        "best_time": "With food, avoid with calcium/iron supplements",
    },
    "magnesium": {
        "name": "Magnesium Supplement",
        "brands": ["Magnex", "Magnerich", "Slow Mag"],
        "category": "Mineral Supplement",
        "uses": ["Muscle cramps", "Sleep", "Migraine prevention", "Constipation (citrate form)", "Anxiety", "Heart health"],
        "adult_dose": "200-400mg daily (elemental magnesium)",
        "child_dose": "As prescribed",
        "pregnancy": "Safe - helps with leg cramps",
        "side_effects": ["Diarrhea (especially citrate)", "Stomach upset"],
        "warnings": ["Different forms: citrate (constipation), glycinate (sleep/anxiety)", "Reduce dose if diarrhea"],
        "best_time": "Evening (helps sleep and muscle relaxation)",
    },
    "probiotics": {
        "name": "Probiotics",
        "brands": ["Culturelle", "Align", "Enterogermina", "VSL#3"],
        "category": "Supplement - Gut Health",
        "uses": ["Gut health", "After antibiotics", "IBS", "Diarrhea", "Immunity"],
        "adult_dose": "1-2 capsules daily (varies by brand)",
        "child_dose": "As prescribed (specific strains for children)",
        "pregnancy": "Generally safe",
        "side_effects": ["Gas (temporary)", "Bloating (first few days)"],
        "warnings": ["Start with low dose", "Take with food", "Separate from antibiotics by 2 hours"],
        "storage": "Some require refrigeration - check label",
    },
    
    # ==========================================
    # SKIN MEDICINES
    # ==========================================
    "hydrocortisone": {
        "name": "Hydrocortisone Cream",
        "brands": ["Cortaid", "Cortizone", "Hycort"],
        "category": "Topical Steroid (Mild)",
        "uses": ["Eczema", "Rashes", "Insect bites", "Itching", "Skin inflammation"],
        "adult_dose": "Apply thin layer 1-3 times daily",
        "child_dose": "As prescribed (use lowest strength)",
        "pregnancy": "Generally safe short-term",
        "side_effects": ["Thinning skin (long-term)", "Stretch marks", "Acne"],
        "warnings": ["Short-term use only (1-2 weeks)", "Don't use on face without doctor advice", "Don't cover with bandage"],
    },
    "miconazole": {
        "name": "Miconazole",
        "brands": ["Daktarin", "Monistat", "Micatin"],
        "category": "Antifungal",
        "uses": ["Athlete's foot", "Ringworm", "Jock itch", "Yeast infections", "Nail fungus"],
        "adult_dose": "Apply 2 times daily for 2-4 weeks",
        "child_dose": "As prescribed (over 2 years)",
        "pregnancy": "Generally safe (topical)",
        "side_effects": ["Local irritation", "Burning", "Redness"],
        "warnings": ["Complete full course even if improved", "Keep area clean and dry"],
    },
    "tretinoin": {
        "name": "Tretinoin (Retin-A)",
        "brands": ["Retin-A", "Retino-A", "Tretin"],
        "category": "Topical Retinoid",
        "uses": ["Acne", "Anti-aging", "Skin texture improvement", "Dark spots"],
        "adult_dose": "Apply pea-sized amount at night",
        "child_dose": "As prescribed by dermatologist (usually over 12)",
        "pregnancy": "AVOID - can cause birth defects",
        "side_effects": ["Redness", "Peeling", "Dryness", "Sun sensitivity (initially)"],
        "warnings": ["Start slow (every 2-3 nights)", "Use sunscreen daily", "Avoid waxing", "Initial purging possible"],
        "best_time": "Night time only (inactivated by sunlight)",
        "tip": "Moisturize after 20-30 minutes to reduce irritation",
    },
}